name: styleLint

on: push


jobs:
  super-lint:
    name: Lint Code base
    runs-on: ubuntu-latest
    steps:
      - name: stylelint 
        uses: actions-hub/stylelint@master
        env:
          INDENT_SPACES: 4
          PATTERN: "*.styled.ts"